### ISSUE TITLE
Remove `enum` dependencies

### ISSUE THREAD

**Issue by kkweon** [lucav76/CarND-Capstone#24]
## Summary
- Python 2 doesn't have `enum` which was added in Python 3.4 [source: Python Official Doc](https://docs.python.org/3/library/enum.html).
- It killed the `tl_detector` process

## Possible solutions
- Remove `enum` from [ros/src/tl_detector/infer.py](https://github.com/lucav76/CarND-Capstone/blob/master/ros/src/tl_detector/infer.py#L25-L31)
## Notes
I am surprised that I thought I was running Python 2 until now. 
If it ran without an issue on my computer, it must be Python 3. I'm confused :confused:

```
[WARNING: disk usage in log directory [/home/udacity/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.
Using TensorFlow backend.
Python: 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

TensorFlow:1.3.0
Traceback (most recent call last):
  File "/media/udacity/yousuf/carnd_cap_autogradr/submissions/951262/ros/src/tl_detector/tl_detector.py", line 9, in <module>
    from light_classification.tl_classifier import TLClassifier
  File "/media/udacity/yousuf/carnd_cap_autogradr/submissions/951262/ros/src/tl_detector/light_classification/tl_classifier.py", line 2, in <module>
    from infer import LightDetectionAndClassification, Detection_Model
  File "/media/udacity/yousuf/carnd_cap_autogradr/submissions/951262/ros/src/tl_detector/infer.py", line 25, in <module>
    from enum import Enum
ImportError: No module named enum
[tl_detector-5] process has died [pid 16792, exit code 1, cmd 
/media/udacity/yousuf/carnd_cap_autogradr/submissions/951262/ros/src/tl_detector/tl_detector.py __name:=tl_detector __log:=/home/udacity/.ros/log/d78fa4da-f57b-11e7-9e04-38d547191b51/tl_detector-5.log].
```

**Comment by kkweon** [comment]
Solved #27
